---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/jaca1078/homolog.jacataloguei
    - /bin/cp -r ./* $DEPLOY_PATH/
    - /bin/chmod -R 755 $DEPLOY_PATH
    - /bin/chown -R jaca1078:jaca1078 $DEPLOY_PATH
